Document: rrplayer-fc
Title: Debian rrplayer-fc Manual
Author: <insert document author here>
Abstract: This manual describes what rrplayer-fc is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/rrplayer-fc/rrplayer-fc.sgml.gz

Format: postscript
Files: /usr/share/doc/rrplayer-fc/rrplayer-fc.ps.gz

Format: text
Files: /usr/share/doc/rrplayer-fc/rrplayer-fc.text.gz

Format: HTML
Index: /usr/share/doc/rrplayer-fc/html/index.html
Files: /usr/share/doc/rrplayer-fc/html/*.html

  
